config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {sessions: 'public/sessions', registrations: 'public/registrations'}
  devise_for :admins, controllers: {sessions: 'admins/sessions', passwords: 'admins/passwords', registrations: 'admins/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   namespace :admins do
    get "/" => "homes#top"
    resources :items,  only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update
    ]
    resources :order_details, only: [:update]
   end

   scope module: :public do
    resources :items, only: [:show, :index]
    root to: 'homes#top'
    get "about" => "homes#about"
    get "/customers/:id/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/:id/withdrawal" => "customers#withdrawal", as: "withdrawal"
    resources :customers, only: [:show, :edit, :update ]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :orders, only: [:new, :comfirm, :complete, :create, :index, :show]
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  attachment :image
  has_many :order_details
  has_many :cart_items
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1 , production: 2, ready: 3, sent: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { cannot: 0, waiting: 1 , ready: 2, completion: 3}
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admins_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
    render :edit
  end
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to admins_genres_path
    else
     render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).reverse_order
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).reverse_order
  end
  def new
    @item = Item.new
    @genres = Genre.all
  end
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = '投稿しました'
      redirect_to admins_items_path
    else
      @genres = Genre.all
      render :new
    end
  end
  def show
    @item = Item.find(params[:id])
  end
  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
    render :edit
  end
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_items_path

  end

  private
  def item_params
   params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @orders = Order.all
    @customer = @order.customer
    @order_details = OrderDetail.all
    @oder_detail = OrderDetail.find(params[:id])
  end
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admins_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:payment_status, :status)
  end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    case resource
    when Customer
     items_path
    when Admin
     admins_items_path
    end
   end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-1">
    <h2>ジャンル編集</h2>
     <%= form_with model: @genre, url: admins_genre_path(@genre), method: :patch, local: true do |f| %>
    <div>
     <table class="table">
      <tr>
        <th>ジャンル</th>
        <th><%= f.text_field :name, autofocus: true %></th>
        <th><%= f.submit "変更を保存", class: "btn btn-success btn-sm btn-block update genre" %></th>
        <% end %>
      </tr>
     </table>
    </div>
    </div>
  </div>
</div>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>ジャンル一覧・追加</h2>
      <%= form_with model: @genre, url: admins_genres_path, method: :post,  local: true do |f| %>
        <table class="table">
        <tr>
          <th>ジャンル名</th>
          <th><%= f.text_field :name, placeholder: "ジャンル名" %></th>
          <th><%= f.submit '新規登録', class: "btn btn-success btn-sm btn-block" %></th>
        </tr>
        </table>
      <% end %>

      <div>
       <table class="table">
        <thead>
         <tr>
          <th></th>
          <th>ジャンル</th>
         </tr>
        </thead>
        <tbody>
         <% @genres.each do |genre| %>
         <tr>
          <td><%= genre.name %></td>
          <td></td>
          <td><%= link_to "編集する", edit_admins_genre_path(genre), class:  "btn btn-success btn-sm btn-block"  %></td>
         </tr>
         <% end %>
        </tbody>
       </table>
      </div>
    </div>
  </div>
</div>

app/views/admins/items/edit.html.erb
<div class="container">
  <h2>商品編集</h2>
  <div class="row">
    <div class="col-md-12 d-flex align-items-center justify-content-center">

      <%= form_with model: @item, url: admins_item_path, method: :patch, local: true do |f| %>
     <div class="form-group row">
      <div>
      <label for="inputImage">商品画像</label>
       <%= f.attachment_field :image %>
      </div>
     </div>

     <div class="form-group row">
      <div>
      <label for="inputName">商品名</label>
       <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"商品名" %>
      </div>
     </div>

     <div class="form-group row">
      <div>
      <label for="inputIntroduction">商品説明</label>
       <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"商品説明" %>
      </div>
     </div>

     <div class="form-group row">
      <div>
      <label for="inputGenre">ジャンル</label>
       <%= f.collection_select :genre_id, @genre, :id, :name, prompt: "選択してください" %>
      </div>
     </div>

     <div class="form-group row">
      <div>
      <label for="inputPrice">税抜価格</label>
       <%= f.text_field :price, autofocus: true, id:"inputPrice", placeholder:"税抜価格" %>
      </div>
     </div>

     <div class="form-group row">
      <div>
      <label for="inputIs_active">販売ステータス</label>
      <div>
       <%= f.radio_button :is_active, true %>
       <%= f.label :is_active, '販売中', value: true %>
      </div>
      <div>
       <%= f.radio_button :is_active, false %>
       <%= f.label :is_active, '販売停止中', value: false %>
      </div>
      </div>
     </div>

     <%= f.submit "変更を保存", class: "btn btn-success btn-sm" %>
     <% end %>
   </div>
  </div>
 </div>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
     <h2>商品一覧</h2> <%= link_to "", new_admins_item_path, class: "btn btn-outline-secondary fas fa-plus-circle" %>

      <table class="table">
       <thead>
        <tr>
         <th>商品id</th>
         <th>商品名</th>
         <th>税抜価格</th>
         <th>ジャンル</th>
         <th>ステータス</th>
        </tr>
       </thead>

       <tbody>
        <% @items.each do |item| %>
        <tr>
         <td><%= item.id %></td>
         <td><%= link_to item.name, admins_item_path(item) %></td>
         <td><%= item.price %></td>
         <td><%= item.genre.name %></td>
         <td><%= item.is_active %></td>
        </tr>
        <% end %>
        <%= paginate @items %>
       </tbody>
     </table>
   </div>
  </div>
 </div>

app/views/admins/items/new.html.erb
<div class="container px-5 py-5">
  <div class="row">
    <h2>商品新規登録</h2>
    <div class="col-md-10 offset-md-1">

       <% if @item.errors.any? %>
       <% @item.errors.count %>error prohibited this obj from being saved
       <% @item.errors.full_messages.each do |message| %>
        <%= message %>
       <% end %>
       <% end %>

     <%= form_with model: @item, url: admins_items_path, method: :post, local: true do |f| %>
      <div class="form-group row">
       <table calss="table">
          <tr>
          <th>商品画像</th>
           <td class="field">
            <%= f.attachment_field :image %>
           </td>
          </tr>
          <tr>
          <th>商品名</th>
           <td class="field">
            <%= f.text_field :name %>
           </td>
          </tr>
          <tr>
          <th>商品説明</th>
           <td class="field">
            <%= f.text_area :introduction %>
           </td>
          </tr>
          <tr>
          <th>ジャンル</th>
           <td>
            <%= f.collection_select :genre_id, @genres, :id, :name, prompt: "選択してください" %>
           </td>
          </tr>
          <tr>
          <th>税抜価格</th>
           <td class="field">
            <%= f.text_field :price %>
           </td>
          </tr>
          <tr>
          <th>販売ステータス</th>
           <td>
            <%= f.radio_button :is_active, "sale" %>
            <%= f.label :is_active, "販売中" %>

            <%= f.radio_button :is_active, "suspended" %>
            <%= f.label :is_active, "販売停止中" %>
           </td>
          </tr>
         </table>
         </div>
         <%= f.submit '新規登録', class: "btn btn-success btn-sm " %>
        <% end %>
     </div>
  </div>
</div

app/views/admins/items/show.html.erb
<div class="container">
 <h2>商品詳細</h2>
  <div class="row">
    <div class="col-md-6 d-flex align-items-center justify-content-center">
      <label for="inputImage"></label>
       <%= attachment_image_tag @item, :image, :fill, 100, 100, fallback: "no_image.jpeg" %>
    </div>

    <div class="col-md-6">
      <div class="form-group row">
       <div>
       <label for="inputName">商品名</label>
        <%= @item.name %>
       </div>
      </div>
      <div class="form-group row">
       <div>
       <label for="inputIntroduction">商品説明</label>
        <%= @item.introduction %>
       </div>
      </div>
      <div class="form-group row">
       <div>
       <label for="inputGenre">ジャンル</label>
        <%= @item.genre.name %>
       </div>
      </div>
      <div class="form-group row">
       <div>
        <label for="inputPrice">税込価格（税抜価格）</label>
        <%= @item.price %>
       </div>
      </div>
      <div class="form-group row">
       <div>
       <label for="inputName">販売ステータス</label>
        <%= @item.is_active %>
       </div>
      </div>
      <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-success btn-sm " %>
 　</div>
　</div>
</div>

app/views/admins/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 offset-md-1">
     <h2>注文履歴一覧</h2>
     <table class="table">
       <td class="form-row">
       <td class="form-group col-5">
         <tr>
          <th>注文日</th>
          <th>配送先</th>
          <th>商品名</th>
          <th>支払金額</th>
          <th>ステータス</th>
          <th>注文詳細</th>
         </tr>
        <% @orders.each do |order| %>
         <tr>
          <td><%= order.created_at %></td>
          <td><%= order.postal_code %></br>
              <%= order.address %></br>
              <%= order.name %>
          </td>
          <td><%= @order_detail.item.name %></td>
          <td><%= order.total_payment %></td>
          <td><%= order.status %></td>
          <td><%= link_to "表示する", order_path(@order), class: "btn btn-primary" %></td>
         </tr>
       </td>
       </td>
     </table>
    </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 offset-md-1">
     <h2>注文履歴詳細</h2>
     <table class="table">
       <thead>
        <tr>
         <td>購入者</td>
         <td><%= link_to @customer.last_name, admins_customer_path %><%= link_to @customer.first_name, admins_customer_path %></td>
        </tr>
        <tr>
         <td>注文日</td>
         <td><%= @order.created_at %></td>
        </tr>
        <tr>
         <td>配送先</td>
         <td><%= @order.postal_code %><%= @order.address %><%= @order.name %></td>
        </tr>
        <tr>
         <td>支払方法</td>
         <td><%= @order.payment_method %></td>
        </tr>
        <tr>
         <td>注文ステータス</td>
         <td><%= f.collection_select :order_id, @orders, :id, :status, prompt: "選択してください" %></td>
         <td><%= link_to "更新", admins_order_path(@order), method: :patch, class: "btn btn-success btn-sm update" %></td>
        </tr>
     </thead>
     <tbody>
        <tr>
         <th>商品名</th>
         <th>単価（税込）</th>
         <th>数量</th>
         <th>小計</th>
         <th>製作ステータス</th>
        </tr>
        <% @sum = 0 %>
        <%= @order_details.each do |order_detail| %>
        <tr>
         <td><%= order_detail.item.name %></td>
         <td><%= order_detail.item.with_tax_price %></td>
         <td><%= order_detail.amount %></td>
         <td><%= order_detail.subtotal %> <% @sum += order_detail.subtotal %></td>
         <td>
          <%= f.collection_select :order_detail_id, @order_details, :id, :making_status, prompt: "選択してください" %><%= link_to "更新", admins_order_detail_path(@order_detail), method: :patch, class: "btn btn-success btn-sm update" %>
         </td>
        </tr>
        <% end %>

        <tr>
        <th>商品合計</th>
         <td><%= @sum %></td>
        <th>送料</th>
         <td><%= 800 %></td>
        <th>請求金額</th>
         <td><%= @sum + 800 %></td>
        </tr>
     </tbody>
    </table>
   </div>
  </div>
</div>