config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {sessions: 'public/sessions', registrations: 'public/registrations'}
  devise_for :admins, controllers: {sessions: 'admins/sessions', passwords: 'admins/passwords', registrations: 'admins/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   namespace :admins do
    get "/" => "homes#top"
    resources :items,  only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update
    ]
    resources :order_details, only: [:update]
   end

   scope module: :public do
    resources :items, only: [:show, :index]
    root to: 'homes#top'
    get "about" => "homes#about"
    get "/customers/:id/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/:id/withdrawal" => "customers#withdrawal", as: "withdrawal"
    resources :customers, only: [:show, :edit, :update ]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :orders, only: [:new, :comfirm, :complete, :create, :index, :show]
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
 def index
  @customers = Customer.all.page(params[:page]).reverse_order
 end
 def show
  @customer = Customer.find(params[:id])
 end
 def edit
  @customer = Customer.find(params[:id])
  render :edit
 end
 def update
  @customer = Customer.find(params[:id])
  @customer.update(customer_params)
  redirect_to admins_customers_path
 end

 private
 def customer_params
  params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
 end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/admins/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
    <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
    <%= form_with model: @customer, url: admins_customer_path, method: :patch, local: true do |f| %>
       <div class="form-group row">
        <div>
         <label for="inputId">会員ID</label>
         <%= @customer.id %>
        </div>
       </div>

       <div class="form-group row">
        <div>
        <label for="inputName">氏名</label>
         <%= f.text_field :last_name, autofocus: true, id:"inputLast_name", placeholder:"姓" %>
         <%= f.text_field :first_name, autofocus: true, id:"inputFirst_name", placeholder:"名" %>
        </div>
       </div>

       <div class="form-group row">
        <div>
         <label for="inputName_kana">フリガナ</label>
         <%= f.text_field :last_name_kana, autofocus: true, id:"inputLast_name_kana", placeholder:"セイ" %>
         <%= f.text_field :first_name_kana, autofocus: true, id:"inputFirst_name_kana", placeholder:"メイ" %>
        </div>
       </div>

       <div class="form-group row">
        <div>
         <label for="inputPostal_code">郵便番号</label>
         <%= f.text_field :postal_code, autofocus: true, id:"inputPostal_code", placeholder:"郵便番号" %>
         </div>
       </div>

       <div class="form-group row">
        <div>
         <label for="inputAddress">住所</label>
         <%= f.text_field :address, autofocus: true, id:"inputAddress", placeholder:"住所" %>
        </div>
       </div>

       <div class="form-group row">
        <div>
         <label for="inputTelephone_number">電話番号</label>
         <%= f.text_field :telephone_number, autofocus: true, id:"inputTelephone_number", placeholder:"電話番号" %>
        </div>
       </div>

       <div class="form-group row">
        <div>
         <label for="inputEmail">メールアドレス</label>
         <%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス" %>
        </div>
       </div>

       <div class="form-group row">
        <div>
         <label for="inputIs_active">会員ステータス</label>
         <div>
         <%= f.radio_button :is_active, true %>
         <%= f.label :is_active, '有効', value: true %>

         <%= f.radio_button :is_active, false %>
         <%= f.label :is_active, '退会', value: false %>
        </div>
       </div>
      </div>

      <%= f.submit "変更を保存", class: "btn btn-success btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 offset-md-1">
     <h2>会員一覧</h2>
      <table class="table table-hover table inverse">
       <thead>
        <tr>
         <th>会員ID</th>
         <th>氏名</th>
         <th>メールアドレス</th>
         <th>ステータス</th>
        </tr>
       </thead>

       <tbody>
        <% @customers.each do |customer| %>
        <tr>
         <td><%= customer.id %></td>
         <td><%= link_to customer.last_name, admins_customer_path(customer) %><%= link_to customer.first_name, admins_customer_path(customer) %></td>
         <td><%= customer.email %></td>
         <td><%= customer.is_active %></td>
        </tr>
       <% end %>
       <%= paginate @customers %>
       </tbody>
      </table>
   </div>
  </div>
</div>

app/views/admins/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1">
     <h2> <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
      <div class="form-group row">
       <div>
        <label for="inputId">会員ID</label>
        <%= @customer.id %>
       </div>
      </div>

      <div class="form-group row">
       <div>
        <label for="inputName">氏名</label>
        <%= @customer.last_name %>
        <%= @customer.first_name %>
       </div>
      </div>

      <div class="form-group row">
       <div>
        <label for="inputName_kana">フリガナ</label>
         <%= @customer.last_name_kana %>
         <%= @customer.first_name_kana %>
       </div>
      </div>

      <div class="form-group row">
       <div>
        <label for="inputPostal_code">郵便番号</label>
        <%= @customer.postal_code %>
       </div>
      </div>

      <div class="form-group row">
       <div>
        <label for="inputAddress">住所</label>
        <%= @customer.address %>
       </div>
      </div>

      <div class="form-group row">
       <div>
        <label for="inputTelephone_number">電話番号</label>
        <%= @customer.telephone_number %>
       </div>
      </div>

      <div class="form-group row">
       <div>
        <label for="inputEmail">メールアドレス</label>
        <%= @customer.email %>
       </div>
      </div>

      <div class="form-group row">
       <div>
        <label for="inputIs_active">会員ステータス</label>
        <%= @customer.is_active %>
       </div>
      </div>

      <%= link_to "編集する", edit_admins_customer_path(@customer), class: "btn btn-success edit genre" %>
      <%= link_to "注文履歴一覧を見る", admins_path, class: "btn btn-primary" %>
     </div>
   </div>
 </div>