config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {sessions: 'public/sessions', registrations: 'public/registrations'}
  devise_for :admins, controllers: {sessions: 'admins/sessions', passwords: 'admins/passwords', registrations: 'admins/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   namespace :admins do
    get "/" => "homes#top"
    resources :items,  only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update
    ]
    resources :order_details, only: [:update]
   end

   scope module: :public do
    resources :items, only: [:show, :index]
    root to: 'homes#top'
    get "about" => "homes#about"
    get "/customers/:id/unsubscribe" => "customers#unsubscribe", as: "unsubscribe"
    patch "/customers/:id/withdrawal" => "customers#withdrawal", as: "withdrawal"
    resources :customers, only: [:show, :edit, :update ]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :orders, only: [:new, :comfirm, :complete, :create, :index, :show]
    post "/orders/confirm" => "orders#confirm", as: "confirm"
    get "/orders/complete" => "orders#complete", as: "complete"
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :addresses
  has_many :orders
end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  attachment :image
  has_many :order_details
  has_many :cart_items
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirmation: 1 , production: 2, ready: 3, sent: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { cannot: 0, waiting: 1 , ready: 2, completion: 3}
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admins_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
    render :edit
  end
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to admins_genres_path
    else
     render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).reverse_order
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).reverse_order
  end
  def new
    @item = Item.new
    @genres = Genre.all
  end
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = '投稿しました'
      redirect_to admins_items_path
    else
      @genres = Genre.all
      render :new
    end
  end
  def show
    @item = Item.find(params[:id])
  end
  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
    render :edit
  end
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_items_path

  end

  private
  def item_params
   params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    case resource
    when Customer
     items_path
    when Admin
     admins_items_path
    end
   end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
   <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand p-3" href="/">LOGO</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
           <% if admin_signed_in? %>
           <li class="nav-item">
            <%= link_to "商品一覧", admins_items_path, class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "会員一覧", admins_customers_path, class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "注文履歴一覧", admins_path, class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "ジャンル一覧", admins_genres_path, class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark'  %>
           </li>

           <% elsif customer_signed_in? %>
           <li class="nav-item">
            <%= link_to "マイページ", customer_path(current_customer.id), class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "商品一覧", items_path, class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
           </li>
           <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark'  %>
           </li>

           <% else %>
           <li class="nav-item">
            <%= link_to "About", "/about", class: 'nav-link text-dark'  %>
           </li>
            <li class="nav-item">
            <%= link_to "商品一覧", "/items", class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark'  %>
           </li>
           <li class="nav-item">
            <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark'  %>
           </li>
           <% end %>

         </ul>
        </div>
       </div>
      </nav>
     </header>
     <main class="mb-auto">
      <%= yield %>
     </main>
   </body>
</html>